# Generated by Django 5.2.17 on 2026-09-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0004_orderplacedrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrecord',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
