# Generated by Django 5.2.17 on 2026-09-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_orderlinerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrecord',
            name='placed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
