# Generated by Django 5.2.17 on 2026-09-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_orderrecord_placed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlacedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField()),
                ('placed_at', models.DateTimeField()),
            ],
        ),
    ]
